In [1]:
import pandas as pd
from statsmodels.formula.api import logit
from plotnine import *
from clean_data import *

In [2]:
df = pd.read_csv("data/loan_level_500k.csv", low_memory=False, index_col=19)
df.head()

,CREDIT_SCORE,FIRST_PAYMENT_DATE,FIRST_TIME_HOMEBUYER_FLAG,MATURITY_DATE,METROPOLITAN_STATISTICAL_AREA,MORTGAGE_INSURANCE_PERCENTAGE,NUMBER_OF_UNITS,OCCUPANCY_STATUS,ORIGINAL_COMBINED_LOAN_TO_VALUE,ORIGINAL_DEBT_TO_INCOME_RATIO,...,PROPERTY_STATE,PROPERTY_TYPE,POSTAL_CODE,LOAN_PURPOSE,ORIGINAL_LOAN_TERM,NUMBER_OF_BORROWERS,SELLER_NAME,SERVICER_NAME,PREPAID,DELINQUENT
LOAN_SEQUENCE_NUMBER,,,,,,,,,,,,,,,,,,,,,
F199Q1000004,669.0,200206,N,202901,NaN,0.0,1.0,O,80.0,33.0,...,WV,SF,26100.0,P,320,2.0,Other sellers,Other servicers,True,False
F199Q1000005,732.0,199904,N,202903,17140.0,0.0,1.0,O,25.0,10.0,...,OH,SF,45200.0,N,360,1.0,Other sellers,Other servicers,True,False
F199Q1000007,679.0,200208,N,202902,15940.0,30.0,1.0,O,91.0,48.0,...,OH,SF,44700.0,P,319,1.0,Other sellers,Other servicers,True,False
F199Q1000013,721.0,200209,N,202902,38060.0,0.0,1.0,O,39.0,13.0,...,AZ,SF,85200.0,N,318,2.0,Other sellers,Other servicers,True,False
F199Q1000015,618.0,200210,N,202902,10420.0,25.0,1.0,O,85.0,24.0,...,OH,SF,44200.0,N,317,2.0,Other sellers,Other servicers,True,False

In [3]:
df = tidy_data(df)
df.head()

,CREDIT_SCORE,FIRST_TIME_HOMEBUYER_FLAG,METROPOLITAN_STATISTICAL_AREA,MORTGAGE_INSURANCE_PERCENTAGE,NUMBER_OF_UNITS,OCCUPANCY_STATUS,ORIGINAL_COMBINED_LOAN_TO_VALUE,ORIGINAL_DEBT_TO_INCOME_RATIO,ORIGINAL_UPB,ORIGINAL_LOAN_TO_VALUE,...,ORIGINAL_LOAN_TERM,NUMBER_OF_BORROWERS,SELLER_NAME,SERVICER_NAME,PREPAID,DELINQUENT,MATURITY_YEAR,MATURITY_MON,FIRST_PAYMENT_YEAR,FIRST_PAYMENT_MON
LOAN_SEQUENCE_NUMBER,,,,,,,,,,,,,,,,,,,,,
F199Q1000004,669.0,N,NaN,0.0,1.0,O,80.0,33.0,162000,80.0,...,320,2.0,Other sellers,Other servicers,True,False,2029,1,2002,6
F199Q1000005,732.0,N,17140.0,0.0,1.0,O,25.0,10.0,53000,25.0,...,360,1.0,Other sellers,Other servicers,True,False,2029,3,1999,4
F199Q1000007,679.0,N,15940.0,30.0,1.0,O,91.0,48.0,133000,91.0,...,319,1.0,Other sellers,Other servicers,True,False,2029,2,2002,8
F199Q1000013,721.0,N,38060.0,0.0,1.0,O,39.0,13.0,174000,39.0,...,318,2.0,Other sellers,Other servicers,True,False,2029,2,2002,9
F199Q1000015,618.0,N,10420.0,25.0,1.0,O,85.0,24.0,122000,85.0,...,317,2.0,Other sellers,Other servicers,True,False,2029,2,2002,10

In [4]:
df['DELINQUENT_ENCODING'] = [1 if i else 0 for i in df['DELINQUENT']]

In [5]:
sample = df.sample(frac=.1)
sample.head()

,CREDIT_SCORE,FIRST_TIME_HOMEBUYER_FLAG,METROPOLITAN_STATISTICAL_AREA,MORTGAGE_INSURANCE_PERCENTAGE,NUMBER_OF_UNITS,OCCUPANCY_STATUS,ORIGINAL_COMBINED_LOAN_TO_VALUE,ORIGINAL_DEBT_TO_INCOME_RATIO,ORIGINAL_UPB,ORIGINAL_LOAN_TO_VALUE,...,NUMBER_OF_BORROWERS,SELLER_NAME,SERVICER_NAME,PREPAID,DELINQUENT,MATURITY_YEAR,MATURITY_MON,FIRST_PAYMENT_YEAR,FIRST_PAYMENT_MON,DELINQUENT_ENCODING
LOAN_SEQUENCE_NUMBER,,,,,,,,,,,,,,,,,,,,,
F102Q1115119,740.0,N,42644.0,0.0,1.0,O,90.0,41.0,214000,80.0,...,2.0,"ABNAMROMTGEGROUP,INC",CHASEMTGECO,True,False,2032,3,2002,4,0
F102Q1061019,755.0,NaN,40900.0,25.0,1.0,I,90.0,35.0,99000,90.0,...,2.0,WELLSFARGOHOMEMORTGA,WELLSFARGOHOMEMORTGA,True,False,2032,2,2002,3,0
F199Q1204144,694.0,N,38900.0,0.0,1.0,O,75.0,34.0,225000,75.0,...,2.0,G N MORTGAGE CORPORA,"BANKOFAMERICA,NA",True,False,2029,3,1999,4,0
F102Q1012430,606.0,N,39140.0,30.0,1.0,O,95.0,44.0,80000,95.0,...,2.0,Other sellers,NATLCITYMTGECO,True,False,2032,2,2002,3,0
F199Q1396435,659.0,N,16860.0,25.0,1.0,O,86.0,31.0,239000,86.0,...,1.0,Other sellers,"SUNTRUSTMORTGAGE,INC",True,False,2029,3,1999,4,0

In [7]:
sample.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50014 entries, F102Q1115119 to F100Q1094215
Data columns (total 29 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   CREDIT_SCORE                      49764 non-null  float64
 1   FIRST_TIME_HOMEBUYER_FLAG         36937 non-null  object
 2   METROPOLITAN_STATISTICAL_AREA     43170 non-null  float64
 3   MORTGAGE_INSURANCE_PERCENTAGE     44940 non-null  float64
 4   NUMBER_OF_UNITS                   50014 non-null  float64
 5   OCCUPANCY_STATUS                  50014 non-null  object
 6   ORIGINAL_COMBINED_LOAN_TO_VALUE   50013 non-null  float64
 7   ORIGINAL_DEBT_TO_INCOME_RATIO     48526 non-null  float64
 8   ORIGINAL_UPB                      50014 non-null  int64
 9   ORIGINAL_LOAN_TO_VALUE            50013 non-null  float64
 10  ORIGINAL_INTEREST_RATE            50014 non-null  float64
 11  CHANNEL                           50014 non-null  object
 12  PREPAYMENT_PENALTY_MORTGAGE_FLAG  49501 non-null  object
 13  PRODUCT_TYPE                      50014 non-null  object
 14  PROPERTY_STATE                    50014 non-null  object
 15  PROPERTY_TYPE                     50007 non-null  object
 16  POSTAL_CODE                       50009 non-null  float64
 17  LOAN_PURPOSE                      50014 non-null  object
 18  ORIGINAL_LOAN_TERM                50014 non-null  int64
 19  NUMBER_OF_BORROWERS               49989 non-null  float64
 20  SELLER_NAME                       50014 non-null  object
 21  SERVICER_NAME                     50014 non-null  object
 22  PREPAID                           50014 non-null  bool
 23  DELINQUENT                        50014 non-null  bool
 24  MATURITY_YEAR                     50014 non-null  int64
 25  MATURITY_MON                      50014 non-null  int64
 26  FIRST_PAYMENT_YEAR                50014 non-null  int64
 27  FIRST_PAYMENT_MON                 50014 non-null  int64
 28  DELINQUENT_ENCODING               50014 non-null  int64
dtypes: bool(2), float64(10), int64(7), object(10)
memory usage: 10.8+ MB

In [37]:
reg = logit('DELINQUENT_ENCODING ~ CREDIT_SCORE + FIRST_TIME_HOMEBUYER_FLAG + METROPOLITAN_STATISTICAL_AREA + MORTGAGE_INSURANCE_PERCENTAGE + NUMBER_OF_UNITS + OCCUPANCY_STATUS + ORIGINAL_COMBINED_LOAN_TO_VALUE + ORIGINAL_DEBT_TO_INCOME_RATIO + ORIGINAL_UPB + ORIGINAL_LOAN_TO_VALUE + ORIGINAL_INTEREST_RATE + CHANNEL + PREPAYMENT_PENALTY_MORTGAGE_FLAG + PRODUCT_TYPE + PROPERTY_TYPE + POSTAL_CODE + LOAN_PURPOSE + ORIGINAL_LOAN_TERM + NUMBER_OF_BORROWERS + SELLER_NAME + SERVICER_NAME + PREPAID + MATURITY_YEAR + MATURITY_MON + FIRST_PAYMENT_YEAR + FIRST_PAYMENT_MON', df).fit()

# excluded PROPERTY_STATE

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.086347
         Iterations: 35

/Users/amulya/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:568: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)

In [38]:
reg.summary()

/Users/amulya/anaconda3/lib/python3.7/site-packages/statsmodels/base/model.py:1354: RuntimeWarning: invalid value encountered in sqrt
  bse_ = np.sqrt(np.diag(self.cov_params()))
/Users/amulya/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
/Users/amulya/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
/Users/amulya/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)

<class 'statsmodels.iolib.summary.Summary'>
"""
                            Logit Regression Results
===============================================================================
Dep. Variable:     DELINQUENT_ENCODING   No. Observations:               280973
Model:                           Logit   Df Residuals:                   280871
Method:                            MLE   Df Model:                          101
Date:                 Mon, 11 May 2020   Pseudo R-squ.:                  0.4316
Time:                         21:03:49   Log-Likelihood:                -24261.
converged:                       False   LL-Null:                       -42681.
Covariance Type:             nonrobust   LLR p-value:                     0.000
=========================================================================================================
                                            coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
Intercept                               135.7587     50.913      2.666      0.008      35.971     235.546
FIRST_TIME_HOMEBUYER_FLAG[T.Y]           -0.0709      0.042     -1.676      0.094      -0.154       0.012
OCCUPANCY_STATUS[T.O]                    -0.0215      0.075     -0.288      0.774      -0.168       0.125
OCCUPANCY_STATUS[T.S]                     0.2318      0.140      1.657      0.098      -0.042       0.506
CHANNEL[T.C]                             -1.2474      1.013     -1.231      0.218      -3.234       0.739
CHANNEL[T.R]                             -0.5395      0.655     -0.824      0.410      -1.823       0.744
CHANNEL[T.T]                             -0.4331      0.655     -0.661      0.509      -1.717       0.851
PREPAYMENT_PENALTY_MORTGAGE_FLAG[T.Y]    -0.1819      0.179     -1.015      0.310      -0.533       0.169
PROPERTY_TYPE[T.CP]                      -1.2969      0.538     -2.411      0.016      -2.351      -0.243
PROPERTY_TYPE[T.LH]                       0.9778      0.565      1.730      0.084      -0.130       2.086
PROPERTY_TYPE[T.MH]                       0.1700      0.187      0.911      0.362      -0.196       0.536
PROPERTY_TYPE[T.PU]                       0.3608      0.073      4.947      0.000       0.218       0.504
PROPERTY_TYPE[T.SF]                       0.4680      0.060      7.819      0.000       0.351       0.585
LOAN_PURPOSE[T.N]                        -0.1698      0.040     -4.202      0.000      -0.249      -0.091
LOAN_PURPOSE[T.P]                        -0.4364      0.043    -10.117      0.000      -0.521      -0.352
SELLER_NAME[T.ACCUBANC MORTGAGE CO]      -0.3491      0.217     -1.612      0.107      -0.773       0.075
SELLER_NAME[T.BANKAMERICA MORTGAGE]       0.3367      0.241      1.399      0.162      -0.135       0.808
SELLER_NAME[T.BANKOFAMERICA,NA]           0.1561      0.131      1.195      0.232      -0.100       0.412
SELLER_NAME[T.BISHOP'S GATE RESIDE]       0.0853      0.142      0.603      0.547      -0.192       0.363
SELLER_NAME[T.BISHOPSGATERESIDENTI]      -0.3389      0.193     -1.752      0.080      -0.718       0.040
SELLER_NAME[T.BRANCHBANKING&TRUSTC]       0.1053      0.499      0.211      0.833      -0.874       1.084
SELLER_NAME[T.CHASE MANHATTAN MORT]       0.3929      0.156      2.520      0.012       0.087       0.698
SELLER_NAME[T.CHASEMANHATTANMTGECO]       0.0902      0.102      0.885      0.376      -0.109       0.290
SELLER_NAME[T.COUNTRYWIDE]               -0.6574      0.213     -3.090      0.002      -1.074      -0.240
SELLER_NAME[T.COUNTRYWIDE HOME LOA]      -0.0419      0.134     -0.313      0.754      -0.304       0.221
SELLER_NAME[T.CROSSLAND MORTGAGE C]       0.4613      0.141      3.281      0.001       0.186       0.737
SELLER_NAME[T.CROSSLANDMTGECORP]          0.4114      0.203      2.023      0.043       0.013       0.810
SELLER_NAME[T.FIFTHTHIRDBANK]            -1.3320      0.462     -2.883      0.004      -2.237      -0.427
SELLER_NAME[T.FIRST UNION CAPITAL]        0.4306      0.165      2.606      0.009       0.107       0.755
SELLER_NAME[T.FIRST UNION MORTGAGE]       0.0162      0.334      0.049      0.961      -0.639       0.671
SELLER_NAME[T.FIRSTARBANK,NA]            -0.0723      0.131     -0.551      0.581      -0.329       0.185
SELLER_NAME[T.FIRSTHORIZONHOMELOAN]       0.1697      0.154      1.104      0.270      -0.132       0.471
SELLER_NAME[T.FLAGSTAR BANK, FSB]         0.1958      0.182      1.075      0.282      -0.161       0.553
SELLER_NAME[T.FLAGSTARBANK,FSB]           0.2190      0.170      1.289      0.198      -0.114       0.552
SELLER_NAME[T.FLEET MORTGAGE CORPO]       0.1218      0.119      1.022      0.307      -0.112       0.356
SELLER_NAME[T.FT MORTGAGE COMPANIE]       0.5348      0.170      3.153      0.002       0.202       0.867
SELLER_NAME[T.G N MORTGAGE CORPORA]       0.7320      0.177      4.143      0.000       0.386       1.078
SELLER_NAME[T.GMAC MORTGAGE CORPOR]      -0.0445      0.179     -0.249      0.804      -0.395       0.306
SELLER_NAME[T.GNMTGECORP]                -0.1020      0.336     -0.304      0.761      -0.761       0.557
SELLER_NAME[T.HOMESIDE LENDING, IN]       0.0967      0.272      0.355      0.723      -0.437       0.631
SELLER_NAME[T.HSBCMTGECORPUSA]           -0.4259      0.289     -1.473      0.141      -0.993       0.141
SELLER_NAME[T.NAMCO ASSET MANAGEME]       0.4481      0.129      3.483      0.000       0.196       0.700
SELLER_NAME[T.NATIONAL CITY MORTGA]       0.1039      0.209      0.498      0.618      -0.305       0.513
SELLER_NAME[T.NATIONSBANC MORTGAGE]       0.1590      0.222      0.716      0.474      -0.276       0.594
SELLER_NAME[T.NATIONSBANK, N.A.]         -0.8117      0.254     -3.190      0.001      -1.310      -0.313
SELLER_NAME[T.NATLCITYMTGECO]            -0.1916      0.133     -1.443      0.149      -0.452       0.069
SELLER_NAME[T.NORWEST MORTGAGE, IN]       0.1957      0.148      1.321      0.186      -0.095       0.486
SELLER_NAME[T.NORWESTMORTGAGE,INC]        0.1666      0.142      1.173      0.241      -0.112       0.445
SELLER_NAME[T.OLD KENT MORTGAGE CO]       0.2310      0.224      1.030      0.303      -0.209       0.671
SELLER_NAME[T.OLDKENTMTGECO]             -0.3479      0.206     -1.687      0.092      -0.752       0.056
SELLER_NAME[T.Other sellers]             -0.0745      0.067     -1.105      0.269      -0.207       0.058
SELLER_NAME[T.PNC MORTGAGE CORPORA]      -0.1898      0.310     -0.613      0.540      -0.797       0.417
SELLER_NAME[T.PNCMTGECORPOFAMERICA]      -0.0083      0.209     -0.039      0.968      -0.419       0.402
SELLER_NAME[T.PRINCIPAL RESIDENTIA]       0.5420      0.223      2.433      0.015       0.105       0.979
SELLER_NAME[T.PRINCIPALRESIDENTIAL]       0.2292      0.158      1.453      0.146      -0.080       0.538
SELLER_NAME[T.PROVIDENTFUNDINGASSO]   -4.683e+04   5.26e+11  -8.91e-08      1.000   -1.03e+12    1.03e+12
SELLER_NAME[T.RESOURCE BANCSHARES]       -0.1979      0.282     -0.701      0.483      -0.751       0.355
SELLER_NAME[T.STANDARD FEDERAL BAN]       0.2228      0.091      2.457      0.014       0.045       0.401
SELLER_NAME[T.SUNTRUSTMORTGAGE,INC]      -0.0239      0.132     -0.181      0.856      -0.283       0.235
SELLER_NAME[T.USBANKNA]                  -0.1366      0.247     -0.553      0.580      -0.621       0.347
SELLER_NAME[T.WASHINGTON MUTUAL BA]       0.2063      0.198      1.043      0.297      -0.182       0.594
SELLER_NAME[T.WELLSFARGOHOMEMORTGA]       0.1078      0.120      0.900      0.368      -0.127       0.343
SERVICER_NAME[T.BAMORTGAGE,LLC]          -0.4953      0.191     -2.599      0.009      -0.869      -0.122
SERVICER_NAME[T.BANKOFAMERICA,NA]        -0.3552      0.107     -3.314      0.001      -0.565      -0.145
SERVICER_NAME[T.BRANCHBANKING&TRUSTC]    -0.1990      0.486     -0.409      0.682      -1.152       0.754
SERVICER_NAME[T.CHASEHOMEFINANCELLC]      1.1687      0.095     12.306      0.000       0.983       1.355
SERVICER_NAME[T.CHASEMANHATTANMTGECO]     0.2070      0.108      1.916      0.055      -0.005       0.419
SERVICER_NAME[T.CHASEMTGECO]             -0.5033      0.096     -5.267      0.000      -0.691      -0.316
SERVICER_NAME[T.CITIMORTGAGE,INC]         0.5583      0.078      7.124      0.000       0.405       0.712
SERVICER_NAME[T.COUNTRYWIDE]              0.4655      0.136      3.428      0.001       0.199       0.732
SERVICER_NAME[T.FIFTHTHIRDBANK]           0.5376      0.168      3.195      0.001       0.208       0.867
SERVICER_NAME[T.FIRSTNATIONWIDEMTGEC]    -1.4039      0.594     -2.363      0.018      -2.568      -0.240
SERVICER_NAME[T.FTMTGESERVICES,INC]      -0.6925      0.189     -3.665      0.000      -1.063      -0.322
SERVICER_NAME[T.GMACMTGECORP]             0.1978      0.154      1.287      0.198      -0.103       0.499
SERVICER_NAME[T.HOMESIDELENDING,INC]     -0.2416      0.192     -1.258      0.208      -0.618       0.135
SERVICER_NAME[T.HSBCMTGECORPUSA]          0.3800      0.352      1.079      0.281      -0.310       1.070
SERVICER_NAME[T.JPMORGANCHASEBANK,NA]    -0.7237      0.115     -6.296      0.000      -0.949      -0.498
SERVICER_NAME[T.NATLCITYMTGECO]           0.2105      0.139      1.510      0.131      -0.063       0.484
SERVICER_NAME[T.OLDKENTMTGECO]           -0.2916      0.619     -0.471      0.638      -1.505       0.922
SERVICER_NAME[T.Other servicers]          0.0089      0.070      0.128      0.898      -0.128       0.146
SERVICER_NAME[T.PRINCIPALRESIDENTIAL]    -0.6834      0.191     -3.574      0.000      -1.058      -0.309
SERVICER_NAME[T.PROVIDENTFUNDINGASSO]  4.683e+04   5.26e+11   8.91e-08      1.000   -1.03e+12    1.03e+12
SERVICER_NAME[T.SUNTRUSTMORTGAGE,INC]    -0.4020      0.168     -2.391      0.017      -0.732      -0.072
SERVICER_NAME[T.USBANKNA]                 0.5210      0.327      1.594      0.111      -0.120       1.162
SERVICER_NAME[T.WASHINGTONMUTUALBANK]     0.2828      0.069      4.105      0.000       0.148       0.418
SERVICER_NAME[T.WELLSFARGOBANK,NA]        0.5810      0.115      5.055      0.000       0.356       0.806
SERVICER_NAME[T.WELLSFARGOHOMEMORTGA]    -0.8805      0.131     -6.742      0.000      -1.137      -0.625
PREPAID[T.True]                          -4.1459      0.033   -125.202      0.000      -4.211      -4.081
CREDIT_SCORE                             -0.0147      0.000    -58.139      0.000      -0.015      -0.014
METROPOLITAN_STATISTICAL_AREA         -2.481e-06   1.18e-06     -2.111      0.035   -4.78e-06   -1.78e-07
MORTGAGE_INSURANCE_PERCENTAGE             0.0075      0.002      4.607      0.000       0.004       0.011
NUMBER_OF_UNITS                           0.0137      0.072      0.189      0.850      -0.128       0.156
ORIGINAL_COMBINED_LOAN_TO_VALUE           0.0193      0.007      2.642      0.008       0.005       0.034
ORIGINAL_DEBT_TO_INCOME_RATIO             0.0136      0.001     10.555      0.000       0.011       0.016
ORIGINAL_UPB                          -6.713e-07   2.65e-07     -2.537      0.011   -1.19e-06   -1.53e-07
ORIGINAL_LOAN_TO_VALUE                    0.0053      0.008      0.693      0.489      -0.010       0.020
ORIGINAL_INTEREST_RATE                    0.3328      0.026     13.007      0.000       0.283       0.383
POSTAL_CODE                           -2.931e-07   4.97e-07     -0.590      0.555   -1.27e-06     6.8e-07
ORIGINAL_LOAN_TERM                        0.1266      0.019      6.661      0.000       0.089       0.164
NUMBER_OF_BORROWERS                      -0.5804      0.027    -21.142      0.000      -0.634      -0.527
MATURITY_YEAR                            -1.3084        nan        nan        nan         nan         nan
MATURITY_MON                             -0.1043        nan        nan        nan         nan         nan
FIRST_PAYMENT_YEAR                        1.2406        nan        nan        nan         nan         nan
FIRST_PAYMENT_MON                         0.0912      0.066      1.384      0.166      -0.038       0.220
=========================================================================================================
"""

In [39]:
reg = logit('DELINQUENT_ENCODING ~ CREDIT_SCORE + ORIGINAL_COMBINED_LOAN_TO_VALUE + ORIGINAL_UPB + ORIGINAL_LOAN_TO_VALUE + ORIGINAL_INTEREST_RATE + POSTAL_CODE', df).fit()
reg.summary()

Optimization terminated successfully.
         Current function value: 0.134717
         Iterations 8

<class 'statsmodels.iolib.summary.Summary'>
"""
                            Logit Regression Results
===============================================================================
Dep. Variable:     DELINQUENT_ENCODING   No. Observations:               497383
Model:                           Logit   Df Residuals:                   497376
Method:                            MLE   Df Model:                            6
Date:                 Mon, 11 May 2020   Pseudo R-squ.:                  0.1284
Time:                         21:13:45   Log-Likelihood:                -67006.
converged:                        True   LL-Null:                       -76876.
Covariance Type:             nonrobust   LLR p-value:                     0.000
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           2.8278      0.141     20.016      0.000       2.551       3.105
CREDIT_SCORE                       -0.0127      0.000    -99.478      0.000      -0.013      -0.012
ORIGINAL_COMBINED_LOAN_TO_VALUE    -0.0469      0.006     -8.158      0.000      -0.058      -0.036
ORIGINAL_UPB                    -9.215e-06   1.64e-07    -56.338      0.000   -9.54e-06   -8.89e-06
ORIGINAL_LOAN_TO_VALUE              0.0772      0.006     13.390      0.000       0.066       0.089
ORIGINAL_INTEREST_RATE              0.1981      0.012     16.594      0.000       0.175       0.221
POSTAL_CODE                     -1.133e-06   2.87e-07     -3.951      0.000    -1.7e-06   -5.71e-07
===================================================================================================
"""